name: Gherkin Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Run tests
        run:  |
          cd app
          flutter test
          
